INSERT INTO compte (idcompte,idproprietaire,type) VALUES (1,70,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (2,48,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (3,87,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (4,5,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (5,63,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (6,67,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (7,75,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (8,87,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (9,3,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (10,87,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (11,69,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (12,34,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (13,89,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (14,82,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (15,56,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (16,6,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (17,52,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (18,9,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (19,57,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (20,95,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (21,28,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (22,70,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (23,51,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (24,49,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (25,25,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (26,79,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (27,70,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (28,52,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (29,32,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (30,32,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (31,36,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (32,24,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (33,11,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (34,70,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (35,17,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (36,61,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (37,59,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (38,92,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (39,2,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (40,70,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (41,80,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (42,24,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (43,20,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (44,13,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (45,88,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (46,9,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (47,24,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (48,100,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (49,69,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (50,96,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (51,98,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (52,17,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (53,78,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (54,70,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (55,68,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (56,82,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (57,65,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (58,63,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (59,91,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (60,94,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (61,73,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (62,92,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (63,50,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (64,9,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (65,60,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (66,99,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (67,94,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (68,19,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (69,62,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (70,72,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (71,60,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (72,49,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (73,82,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (74,14,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (75,57,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (76,62,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (77,46,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (78,67,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (79,34,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (80,43,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (81,73,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (82,12,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (83,38,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (84,70,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (85,86,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (86,15,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (87,17,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (88,48,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (89,51,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (90,75,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (91,47,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (92,88,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (93,25,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (94,56,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (95,29,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (96,81,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (97,92,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (98,12,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (99,48,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (100,87,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (101,29,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (102,97,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (103,56,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (104,36,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (105,68,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (106,51,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (107,28,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (108,44,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (109,71,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (110,5,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (111,77,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (112,18,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (113,94,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (114,46,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (115,31,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (116,17,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (117,63,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (118,42,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (119,5,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (120,100,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (121,19,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (122,28,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (123,69,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (124,86,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (125,46,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (126,54,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (127,34,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (128,30,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (129,91,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (130,98,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (131,64,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (132,56,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (133,32,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (134,52,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (135,91,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (136,26,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (137,89,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (138,95,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (139,92,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (140,45,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (141,39,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (142,69,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (143,21,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (144,71,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (145,15,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (146,94,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (147,68,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (148,51,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (149,34,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (150,55,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (151,98,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (152,10,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (153,81,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (154,90,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (155,15,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (156,72,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (157,68,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (158,9,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (159,63,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (160,26,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (161,47,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (162,38,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (163,18,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (164,14,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (165,33,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (166,49,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (167,25,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (168,83,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (169,87,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (170,5,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (171,72,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (172,87,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (173,92,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (174,61,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (175,58,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (176,83,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (177,96,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (178,10,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (179,79,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (180,44,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (181,12,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (182,82,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (183,47,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (184,37,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (185,90,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (186,53,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (187,63,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (188,61,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (189,26,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (190,78,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (191,52,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (192,93,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (193,16,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (194,37,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (195,8,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (196,72,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (197,17,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (198,30,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (199,31,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (200,12,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (201,82,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (202,51,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (203,49,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (204,94,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (205,91,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (206,65,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (207,35,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (208,92,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (209,42,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (210,29,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (211,72,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (212,39,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (213,30,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (214,60,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (215,58,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (216,40,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (217,21,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (218,54,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (219,3,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (220,40,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (221,33,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (222,38,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (223,97,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (224,15,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (225,69,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (226,65,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (227,7,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (228,2,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (229,22,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (230,74,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (231,13,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (232,30,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (233,94,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (234,47,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (235,84,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (236,28,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (237,95,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (238,10,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (239,60,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (240,6,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (241,87,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (242,46,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (243,69,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (244,55,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (245,39,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (246,57,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (247,76,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (248,30,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (249,82,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (250,52,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (251,82,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (252,39,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (253,39,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (254,15,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (255,12,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (256,62,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (257,26,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (258,17,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (259,92,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (260,45,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (261,94,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (262,61,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (263,46,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (264,47,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (265,92,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (266,25,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (267,19,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (268,96,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (269,25,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (270,15,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (271,51,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (272,89,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (273,52,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (274,7,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (275,96,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (276,55,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (277,77,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (278,12,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (279,45,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (280,42,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (281,62,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (282,87,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (283,82,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (284,5,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (285,26,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (286,76,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (287,44,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (288,30,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (289,86,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (290,3,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (291,25,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (292,27,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (293,67,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (294,38,"Assurance Vie");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (295,92,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (296,83,"Compte Courant");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (297,3,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (298,62,"Plan Epargne Actions");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (299,59,"Livret A");
INSERT INTO compte (idcompte,idproprietaire,type) VALUES (300,81,"Plan Epargne Actions");
